trigger:  
- master

parameters:
- name: name  
  default: 'oss_stage'

- name: 'param'
  type: object
  default: 
  - FOO
  - BAR
  - ZOO

- name: 'ids'
  type: object
  default: 
  - 1
  - 2
  - 3

variables:
- name: one
  value: initialValue 

pool:
  vmImage: ubuntu-latest

stages:
- stage: ${{ parameters.name }}
  jobs:
  - job: oss_job
    steps:   
    - script: | 
      ${{ each p in parameters.param }}:
        echo ${{ p }}      
    - task: AzureCLI@2 #https://learn.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops
      displayName: Azure-PS1
      inputs:
        azureSubscription: niqflex_boards
        scriptType: pscore 
        scriptLocation: inlineScript        
        arguments: '${{ parameters.name }}'      
        inlineScript: './scripts/oss-iac.ps1 $1'           
      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken) 
    - task: AzureCLI@2 
      displayName: Azure-CLI
      inputs:
        azureSubscription: niqflex_boards
        scriptType: pscore 
        scriptLocation: inlineScript        
        arguments: '${{ parameters.name }}'      
        inlineScript: |
           az boards query --wiql "SELECT [System.Title], [System.Description] FROM workitems" --output table --org https://dev.azure.com/niqflex-org            
           $auth = "Bearer $env:System_AccessToken"
           $baseUri = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/";
           $headers = @{Authorization = $auth };
           Write-Host "baseUrl $($baseUri)"       
           #$resp = Invoke-RestMethod -Uri "$($baseUri)_apis/wit/workitems?ids=1" -Method Get -ContentType "application/json" 
           #Write-Host $resp  
           Response = Invoke-WebRequest -Uri https://dev.azure.com/niqflex-org/niqflex/_apis/wit/workitems?ids='1'&api-version=7.1-preview.3
           Write-Host $Response                   
      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken) 

    