# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

parameters:
- name: name  
  default: 'oss_stage'

pool:
  vmImage: ubuntu-latest

stages:
- stage: ${{ parameters.name }}
  jobs:
  - job: oss_job
    steps:
    - task: CmdLine@2 
      displayName: 'Microsoft Security DevOps' 
      inputs:  
        workingDirectory: $(Build.SourcesDirectory)
        script: |
          cd $(Build.SourcesDirectory)
          ls
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host ${{ parameters.name }}
             


