trigger:  
- master

parameters:
- name: name  
  default: 'oss_stage'

variables:
- name: one
  value: initialValue 

pool:
  vmImage: ubuntu-latest

stages:
- stage: ${{ parameters.name }}
  jobs:
  - job: oss_job
    steps:      
    - task: AzureCLI@2 #https://learn.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops
      displayName: Azure CLI
      inputs:
        azureSubscription: niqflex_boards
        scriptType: pscore #bash
        #scriptLocation: inlineScript
        scriptLocation: 'scriptPath'
        arguments: '${{ parameters.name }}'
        #inlineScript: |
        #    './scripts/oss-iac.ps1 $1'  
        scriptPath: './scripts/oss-iac.ps1 $1'    
      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)    